[minecraft]
version = "1.21.1"

[fabric]
loader = "0.18.3"
installer_url = "https://maven.fabricmc.net/net/fabricmc/fabric-installer/1.1.0/fabric-installer-1.1.0.jar"

[[mods]]
name = "sodium"
url  = "https://cdn.modrinth.com/data/AANobbMI/versions/4OZL6q5h/sodium-fabric-0.6.0-beta.2%2Bmc1.21.jar"

[[mods]]
name = "lithium"
url  = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/ZSNsJrPI/lithium-fabric-mc1.21.1-0.13.0.jar"
